# Generated by Django 4.2.5 on 2023-10-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='Update number', max_length=15),
        ),
    ]
