# Generated by Django 4.2.5 on 2023-11-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_date_created_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fav_mov',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Favorite Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='profile_picture\\default.jpg', upload_to='profile_picture', verbose_name='Profile Picture'),
        ),
    ]
